language: cpp

compiler:
  - gcc
  - clang

before_install:
  - source ci/obs_common.sh
  - source ci/obs_before_install.sh

before_script:
  - sudo apt-get install -qq devscripts equivs
  - sudo mk-build-deps -i
  - ./autogen.sh

script:
  - ./configure --prefix=$HOME
  - make clean
  - make
  - make install
  - PYTHONPATH=$HOME/lib/python2.7/site-packages make check
  - source ci/obs_prepare.sh

after_success:
  - source ci/obs_commit.sh

env:
  global:
    - secure: "TesD/DQr5Q0N4dGTgFLYrbVZCJ1/xvxXSfAsNqVTAWn1kG7NBZEVLvB2nfxQRc7f+ata+RNetuk+OV0+mmofgLcN2h6qGDBfPsh/Bk2zi7k1VBIjAoT7uEFB5LSyOQ/fFjAErRFtzgteq1QKlJL+RtJcSs5KyhwBR/fmDi6Zyvw="
    - OBS_HOME=security
    - OBS_PROJECT=Zorp
    - OBS_SUBPROJECT=5.0
    - OBS_PACKAGE=zorp
    - TEST_OS=Ubuntu
    - TEST_OS_VERSION=12.04
    - secure: "dDT9rtWPh8iYO56qWqatuKRE+gk3xEKKZa/sKSAbb/PyHSsJLkDp9vA4e0+JQNStC4YA+X0L6m4bpt275TKee1ucQg47to/monHmr3FG1LAx6zm8Gq7/4PlFnOo1oxfjFZEUnwF/WNZxjf6Y99n65onKl8fUGknGFnAKf0dYxWo="

addons:
  coverity_scan:
    project:
      name: "balabit/zorp"
      version: 5.0.0
      description: "Build submitted via Travis CI"
    notification_email: coroner@pfeifferszilard.hu
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j4"
    branch_pattern: coverity_scan
